name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Login via Az module
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Azure PowerShell script
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Set-AzConext 77f2419f-316b-4263-a550-2e9d3393713e
            Get-AzVM
          azPSVersion: '3.1.0'
