name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

      - name: Login via Az module
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true

      - name: Checkout
        uses: actions/checkout@v1

      - name: Run Azure PowerShell script
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $VbaVms = Get-AzVm -Name "VBA*"
          azPSVersion: '3.1.0'

      - name: 'Output to Github Env'
        run: echo "VBA_VMs=$$VbaVms" >> $GITHUB_ENV

      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Auckland' date '+%Y-%m-%d %T')" >> $GITHUB_ENV

      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: (${{env.REPORT_DATE}}) - LIC - Veeam VBA Status
          body: $VbaVms
          to: jacky.fan@kordia.co.nz
          from: GitHub Actions
          content_type: text/html

      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az logout
            az cache purge
            az account clear
